### ISSUE TITLE
plaincas_custom_groups() needs a fix

### ISSUE THREAD

**Issue by chrisdamato** [esn-org/authplaincas#1]
Thanks for sharing your work! I am new at git, sorry if I am not doing this correctly.

In file plaincas.settings.php function plaincas_custom_groups

the last line:
  return array();
should be:
  return $customGroups;

When I made this fix the plugin worked as described. Thanks again.

**Comment by bircher** [comment]
Hello
Yes, correct! This is half way on purpose though.
The file is supposed to be copied to the configuration folder (or somewhere else) and customized. I wanted it to be configurable in the UI, but it is much easier to complete the few functions. In the cases I used it myself I didn't need the custom groups hence returning a empty array.

But it is true that the documentation is quite poor and it could be a better example if it was just:

``` php
function plaincas_custom_groups(){

 $customGroups = array(
    'group1' => array('username1', 'userame2'),
    'group2' => array('username3', 'userame4'),
  );
  // if no custom groups are needed return an empty array
  $customGroups = array();

  return $customGroups;
}
```

Don't edit the file directly or you will be in trouble should there be an updated version (let me know if something more advanced is needed)
see https://www.dokuwiki.org/plugin:authplaincas
