### ISSUE TITLE
which version of phpCAS?

### ISSUE THREAD

**Issue by robshep** [esn-org/authplaincas#11]
The current version of phpCAS doesn't work with this plugin.

The initial breakage happens due to an extra constructor argument for the client. 

(boolean 'proxy' is expected as arg no. 2, but in the plugin this argument is for the server host)

The link to the master release of phpCAS is possibly 1.3.5, the latest.  
There are security advisories for client lib releases lower than that. 

Which release should we select if we want it to work?

Do you think it might be just the constructor? or more fundamental changes?

Thanks

Using the latest plugin which has:

```
base   authplaincas
author Fabian Bircher
email  fabian@esn.org
date   2016-07-22
name   Plain CAS Auth Plugin
desc   Provides user authentication against a CAS server
url    http://www.dokuwiki.org/plugin:authplaincas
```

**Comment by robshep** [comment]
Client constructor @ 1.3.5

https://github.com/Jasig/phpCAS/blob/1.3.5/source/CAS/Client.php#L902

**Comment by robshep** [comment]
Plugin usage of Client constructor:

https://github.com/jasedit/authplaincas/blob/master/auth.php#L174

**Comment by phy25** [comment]
Is this a reproducable issue?

It seems that what [auth.php:174](https://github.com/jasedit/authplaincas/blob/master/auth.php#L174) is calling is [phpCAS/CAS.php:338](https://github.com/Jasig/phpCAS/blob/master/source/CAS.php#L338), which doesn't have a proxy argument.

**Comment by robshep** [comment]
Sorry, I didn't trace the call properly.  The original issue was an error complaining about CAS conf params missing, (something along the lines of "bad port: http:cas.example.com" which I incorrectly traced back to the Client constructor not the factory. 

In any case, having applied an SSL certificate the CAS server and changed the authplaincas setting to reflect I can't reproduce the issue. Apologies, I'll close this one.
