### ISSUE TITLE
Timeout for "Authentication Security Timeout (seconds)" not working

### ISSUE THREAD

**Issue by nfaction** [esn-org/authplaincas#2]
Hello,
I have been using your plugin for the last few months, and no matter what I set the timeout to, (e.g. 900 in my case), it always logs me out automatically after an hour or two.  Extremely annoying!  I verified that my timeout for our CAS service is set to 24 hours, and it works with every other SSO app that uses CAS except my wiki.  Any ideas on how to fix this?  Seems that no matter what number I put in for the timeout, it kicks me out after an hour or two...
-Matt

**Comment by nfaction** [comment]
Bump...

**Comment by dgeo** [comment]
It may be related with my pull request #5 , could you test this patch ?
https://github.com/criecm/authplaincas/commit/fa47c526b71dfdde0e4f50cd215d11bce33b64ea
