### ISSUE TITLE
custom group in plugin:authplaincas

### ISSUE THREAD

**Issue by jehanproc** [esn-org/authplaincas#4]
Hello,
I did follow https://www.dokuwiki.org/plugin:authplaincas installation guide
did put lib/plugins/authplaincas/phpCAS/CAS.php and cp -a /usr/share/pear/CAS to lib/plugins/authplaincas/phpCAS/
CAS SSO login work fine, but I never get my username associated with a custom group I did define in conf/plaincas.settings.php as follows

function plaincas_custom_groups(){
  $customGroups = array(
    'SSI' => array('jehanproc', 'userame2'),
    'SI' => array('copfin', 'userame4'),
  );
  return array();
}

Whe I login and ask for details with do=check
doku.php?id=start&do=check
I do see my looged in as jehanproc  and I am part of group user (the default group) 
but not in SSI I would expect .

please, let me know what is wrong ?

Regards

**Comment by bircher** [comment]
Hello
Your function needs to return the custom array so write:

``` php
function plaincas_custom_groups(){
    $customGroups = array(
        'SSI' => array('jehanproc', 'userame2'),
        'SI' => array('copfin', 'userame4'),
    );
    return $customGroups;
}
```
