### ISSUE TITLE
authplaincas doesn't work for 2017-02-19b "Frusterick Manners".

### ISSUE THREAD

**Issue by johanv** [esn-org/authplaincas#9]
The problem is that phpCAS replaces the session by a new session, and this new session's ID is only 13 characters long. Dokuwiki doesn't like that (minimum length for session ID is 22), and throws away the session.

This might be an issue with phpCAS.

I created a workaround for dokuwiki (splitbrain/dokuwiki#1904), but I'm not sure whether it should be fixed over there, or in authplaincas itself, or in phpCAS.

**Comment by phy25** [comment]
Seems that `session_id` is from `$ticket2logout`, originally from CAS server..? I think it might be solved from phpCAS upstream because 
> The documentation says sessionIDs are between 22 and 256 chars long. (http://php.net/manual/en/session.configuration.php#ini.session.sid-length)

Code related in phpCAS: https://github.com/Jasig/phpCAS/tree/master/source/CAS/Client.php#L1811

**Comment by jeroenvl** [comment]
Just implemented a temporary workaround, see commit message for details! When phpCAS releases an update, I will make sure to provide another update
